title: Ramesh Chukka
logo: /assets/img/520F57CE-F46B-4BA8-A2E1-E1DB4B3FE9D9_1_201_a.heic
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
